import type { GradeCurriculum } from '../../curriculum/types';

export const GRADE_7_PHYSICS_CURRICULUM: GradeCurriculum = {
  grade: 7,
  title: 'Vật lý lớp 7 (Khoa học tự nhiên 7 - Kết nối tri thức)',
  chapters: [
    {
      id: 'phy-g7-c01',
      chapterNumber: 1,
      title: 'Unit 1 — Tốc độ',
      description: 'Khái niệm tốc độ chuyển động, đo tốc độ, đồ thị quãng đường - thời gian và an toàn giao thông',
      lessons: [
        {
          id: 'phy-g7-b01',
          lessonNumber: 1,
          title: 'Tốc độ chuyển động',
          subtitle: 'Bài 8 SGK: Khái niệm tốc độ, công thức v = s / t và các đơn vị đo tốc độ',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b01-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Tốc độ chuyển động',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b01-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính tốc độ chuyển động',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b02',
          lessonNumber: 2,
          title: 'Đo tốc độ',
          subtitle: 'Bài 9 SGK: Đo tốc độ dùng đồng hồ bấm giây và cổng quang điện với đồng hồ đo thời gian hiện số',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b02-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đo tốc độ',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b02-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Các phương pháp đo tốc độ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b03',
          lessonNumber: 3,
          title: 'Đồ thị quãng đường - thời gian',
          subtitle: 'Bài 10 SGK: Cách vẽ, đọc và khai thác đồ thị quãng đường - thời gian để mô tả chuyển động',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b03-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đồ thị quãng đường - thời gian',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b03-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đọc và phân tích đồ thị s - t',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b04',
          lessonNumber: 4,
          title: 'Thảo luận về ảnh hưởng của tốc độ trong an toàn giao thông',
          subtitle: 'Bài 11 SGK: Tốc độ tối đa cho phép, khoảng cách an toàn và quy tắc giao thông',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b04-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Tốc độ và an toàn giao thông',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b04-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Khoảng cách an toàn & Biển báo tốc độ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g7-b04-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy tốc độ',
              description: 'Thử thách tổng kết Unit 1: Tốc độ',
              type: 'checkpoint',
            },
            {
              id: 'phy-g7-b04-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 1: Tốc độ',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 1',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g7-c02',
      chapterNumber: 2,
      title: 'Unit 2 — Âm thanh',
      description: 'Sự truyền sóng âm trong các môi trường, độ to, độ cao và hiện tượng phản xạ âm',
      lessons: [
        {
          id: 'phy-g7-b05',
          lessonNumber: 5,
          title: 'Sóng âm',
          subtitle: 'Bài 12 SGK: Nguồn âm, sự dao động và sự truyền sóng âm trong chất rắn, lỏng, khí',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b05-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Sóng âm',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b05-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Nguồn âm và môi trường truyền âm',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b06',
          lessonNumber: 6,
          title: 'Độ to và độ cao của âm',
          subtitle: 'Bài 13 SGK: Mối liên hệ giữa biên độ với độ to (dB), tần số (Hz) với độ cao',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b06-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Độ to và độ cao của âm',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b06-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tần số dao động & Biên độ âm',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b07',
          lessonNumber: 7,
          title: 'Phản xạ âm, chống ô nhiễm tiếng ồn',
          subtitle: 'Bài 14 SGK: Âm phản xạ, tiếng vang, vật phản xạ âm tốt/kém và biện pháp chống ô nhiễm tiếng ồn',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b07-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Phản xạ âm & Tiếng ồn',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b07-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Phản xạ âm và các vật liệu cách âm',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g7-b07-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy âm thanh',
              description: 'Thử thách tổng kết Unit 2: Âm thanh',
              type: 'checkpoint',
            },
            {
              id: 'phy-g7-b07-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 2: Âm thanh',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 2',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g7-c03',
      chapterNumber: 3,
      title: 'Unit 3 — Ánh sáng',
      description: 'Năng lượng ánh sáng, tia sáng, định luật phản xạ ánh sáng và ảnh qua gương phẳng',
      lessons: [
        {
          id: 'phy-g7-b08',
          lessonNumber: 8,
          title: 'Năng lượng ánh sáng. Tia sáng, vùng tối',
          subtitle: 'Bài 15 SGK: Năng lượng ánh sáng, chùm sáng, biểu diễn tia sáng, vùng tối và vùng nửa tối',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b08-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng ánh sáng & Tia sáng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b08-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tia sáng, chùm sáng và bóng tối',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b09',
          lessonNumber: 9,
          title: 'Sự phản xạ ánh sáng',
          subtitle: 'Bài 16 SGK: Hiện tượng phản xạ, định luật phản xạ ánh sáng, góc tới bằng góc phản xạ (i = i\')',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b09-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Định luật phản xạ ánh sáng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b09-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính góc tới, góc phản xạ và tia phản xạ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b10',
          lessonNumber: 10,
          title: 'Ảnh của vật qua gương phẳng',
          subtitle: 'Bài 17 SGK: Tính chất ảnh ảo tạo bởi gương phẳng, khoảng cách từ ảnh và vật đến gương',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b10-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Ảnh qua gương phẳng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b10-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Xác định ảnh của vật qua gương phẳng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g7-b10-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy quang học',
              description: 'Thử thách tổng kết Unit 3: Ánh sáng',
              type: 'checkpoint',
            },
            {
              id: 'phy-g7-b10-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 3: Ánh sáng',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 3',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g7-c04',
      chapterNumber: 4,
      title: 'Unit 4 — Từ',
      description: 'Tác dụng từ của nam châm, từ trường, la bàn và chế tạo nam châm điện',
      lessons: [
        {
          id: 'phy-g7-b11',
          lessonNumber: 11,
          title: 'Nam châm',
          subtitle: 'Bài 18 SGK: Các cực của nam châm, tương tác giữa hai nam châm và vật liệu từ',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b11-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Cực nam châm & Tác dụng từ',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b11-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tương tác từ và vật liệu từ tính',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b12',
          lessonNumber: 12,
          title: 'Từ trường',
          subtitle: 'Bài 19 SGK: Không gian có từ trường, từ phổ, đường sức từ và từ trường Trái Đất',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b12-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Từ trường & Đường sức từ',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b12-n01',
              nodeIndex: 2,
              title: 'Luyện tập: La bàn, từ phổ và định hướng từ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g7-b13',
          lessonNumber: 13,
          title: 'Chế tạo nam châm điện đơn giản',
          subtitle: 'Bài 20 SGK: Cấu tạo nam châm điện, các yếu tố ảnh hưởng lực từ và ứng dụng',
          ready: true,
          nodes: [
            {
              id: 'phy-g7-b13-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Nam châm điện & Ứng dụng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g7-b13-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Các bước chế tạo và điều khiển từ tính',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g7-b13-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy từ học',
              description: 'Thử thách tổng kết Unit 4 & Toàn khóa Vật lý 7',
              type: 'checkpoint',
            },
            {
              id: 'phy-g7-b13-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Toàn khóa Vật lý 7',
              description: 'Phần thưởng vinh danh hoàn thành xuất sắc toàn bộ 13 bài Vật lý lớp 7!',
              type: 'chest',
            },
          ],
        },
      ],
    },
  ],
};
