import type { GradeCurriculum } from '../../curriculum/types';

export const GRADE_9_PHYSICS_CURRICULUM: GradeCurriculum = {
  grade: 9,
  title: 'Vật lý lớp 9 (Khoa học tự nhiên 9 - Kết nối tri thức)',
  chapters: [
    {
      id: 'phy-g9-c01',
      chapterNumber: 1,
      title: 'Unit 1 — Năng lượng cơ học',
      description: 'Động năng, thế năng, cơ năng, định luật bảo toàn cơ năng, công cơ học và công suất',
      lessons: [
        {
          id: 'phy-g9-b01',
          lessonNumber: 1,
          title: 'Động năng. Thế năng',
          subtitle: 'Bài 2 SGK: Khái niệm động năng, thế năng trọng trường và các yếu tố ảnh hưởng',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b01-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Động năng & Thế năng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b01-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Phân tích động năng và thế năng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b02',
          lessonNumber: 2,
          title: 'Cơ năng',
          subtitle: 'Bài 3 SGK: Định nghĩa cơ năng, sự chuyển hóa giữa động năng và thế năng, bảo toàn cơ năng',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b02-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Cơ năng và bảo toàn cơ năng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b02-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Sự chuyển hóa và bảo toàn cơ năng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b03',
          lessonNumber: 3,
          title: 'Công và công suất',
          subtitle: 'Bài 4 SGK: Công thức tính công cơ học A = F . s, công suất P = A / t và đơn vị đo',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b03-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Công và công suất',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b03-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính công A và công suất P',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g9-b03-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Năng lượng cơ học',
              description: 'Thử thách tổng kết Unit 1: Năng lượng cơ học',
              type: 'checkpoint',
            },
            {
              id: 'phy-g9-b03-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 1: Cơ học Lớp 9',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 1',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g9-c02',
      chapterNumber: 2,
      title: 'Unit 2 — Ánh sáng',
      description: 'Hiện tượng khúc xạ ánh sáng, phản xạ toàn phần, lăng kính, thấu kính, thực hành đo tiêu cự và kính lúp',
      lessons: [
        {
          id: 'phy-g9-b04',
          lessonNumber: 4,
          title: 'Khúc xạ ánh sáng',
          subtitle: 'Bài 5 SGK: Hiện tượng gãy khúc của tia sáng tại mặt phân cách giữa hai môi trường trong suốt',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b04-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Khúc xạ ánh sáng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b04-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tia tới, tia khúc xạ và góc tới/khúc xạ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b05',
          lessonNumber: 5,
          title: 'Phản xạ toàn phần',
          subtitle: 'Bài 6 SGK: Điều kiện xảy ra phản xạ toàn phần, góc giới hạn và ứng dụng sợi quang học',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b05-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Phản xạ toàn phần',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b05-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Góc giới hạn & Ứng dụng cáp quang',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b06',
          lessonNumber: 6,
          title: 'Lăng kính',
          subtitle: 'Bài 7 SGK: Tác dụng làm lệch tia sáng và hiện tượng tán sắc ánh sáng qua lăng kính',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b06-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Lăng kính và tán sắc ánh sáng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b06-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đường truyền ánh sáng qua lăng kính',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b07',
          lessonNumber: 7,
          title: 'Thấu kính',
          subtitle: 'Bài 8 SGK: Thấu kính hội tụ, thấu kính phân kì, trục chính, quang tâm, tiêu điểm và ảnh tạo bởi thấu kính',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b07-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Thấu kính hội tụ & Phân kì',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b07-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Nhận biết thấu kính & Đường truyền tia sáng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b08',
          lessonNumber: 8,
          title: 'Thực hành đo tiêu cự của thấu kính hội tụ',
          subtitle: 'Bài 9 SGK: Bố trí giá quang học, ngọn nến, thấu kính, màn ảnh và đo tiêu cự f',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b08-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Kĩ năng thực hành đo tiêu cự thấu kính',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b08-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Quy trình đo và xử lý số liệu tiêu cự',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b09',
          lessonNumber: 9,
          title: 'Kính lúp',
          subtitle: 'Bài 10 SGK: Cấu tạo kính lúp, số bội giác G = 25/f và cách quan sát vật nhỏ bằng kính lúp',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b09-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Kính lúp và số bội giác',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b09-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Quan sát vật nhỏ & Tính số bội giác',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g9-b09-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Quang học Lớp 9',
              description: 'Thử thách tổng kết Unit 2: Ánh sáng',
              type: 'checkpoint',
            },
            {
              id: 'phy-g9-b09-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 2: Quang học Lớp 9',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 2',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g9-c03',
      chapterNumber: 3,
      title: 'Unit 3 — Điện',
      description: 'Điện trở, định luật Ohm, đoạn mạch nối tiếp, đoạn mạch song song, công suất điện và điện năng tiêu thụ',
      lessons: [
        {
          id: 'phy-g9-b10',
          lessonNumber: 10,
          title: 'Điện trở. Định luật Ohm',
          subtitle: 'Bài 11 SGK: Khái niệm điện trở, điện trở suất, công thức định luật Ohm I = U / R',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b10-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Điện trở và định luật Ohm',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b10-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Vận dụng định luật Ohm I = U / R',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b11',
          lessonNumber: 11,
          title: 'Đoạn mạch nối tiếp, song song',
          subtitle: 'Bài 12 SGK: Quy tắc tính cường độ dòng điện, hiệu điện thế và điện trở tương đương',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b11-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Mạch điện nối tiếp và song song',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b11-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính điện trở tương đương & Cường độ dòng điện',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b12',
          lessonNumber: 12,
          title: 'Năng lượng của dòng điện và công suất điện',
          subtitle: 'Bài 13 SGK: Công suất điện P = U . I, điện năng tiêu thụ A = P . t và ý nghĩa công tơ điện',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b12-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng điện & Công suất điện',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b12-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính điện năng tiêu thụ & Công suất điện',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g9-b12-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Điện học Lớp 9',
              description: 'Thử thách tổng kết Unit 3: Điện học',
              type: 'checkpoint',
            },
            {
              id: 'phy-g9-b12-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 3: Điện học Lớp 9',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 3',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g9-c04',
      chapterNumber: 4,
      title: 'Unit 4 — Điện từ',
      description: 'Hiện tượng cảm ứng điện từ, máy phát điện xoay chiều, tác dụng của dòng điện xoay chiều và máy biến thế',
      lessons: [
        {
          id: 'phy-g9-b13',
          lessonNumber: 13,
          title: 'Cảm ứng điện từ. Nguyên tắc tạo ra dòng điện xoay chiều',
          subtitle: 'Bài 14 SGK: Điều kiện xuất hiện dòng điện cảm ứng, hiện tượng cảm ứng điện từ và mô hình máy phát điện',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b13-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Cảm ứng điện từ & Dòng điện xoay chiều',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b13-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Nhận biết hiện tượng cảm ứng điện từ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b14',
          lessonNumber: 14,
          title: 'Tác dụng của dòng điện xoay chiều',
          subtitle: 'Bài 15 SGK: Tác dụng nhiệt, quang, từ của dòng xoay chiều, truyền tải điện năng và máy biến thế',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b14-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Tác dụng dòng xoay chiều & Máy biến thế',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b14-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Vận dụng công thức máy biến thế U1/U2 = N1/N2',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g9-b14-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Điện từ học',
              description: 'Thử thách tổng kết Unit 4: Điện từ học',
              type: 'checkpoint',
            },
            {
              id: 'phy-g9-b14-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 4: Điện từ học',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 4',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g9-c05',
      chapterNumber: 5,
      title: 'Unit 5 — Năng lượng với cuộc sống',
      description: 'Vòng năng lượng trên Trái Đất, nhiên liệu hóa thạch và các dạng năng lượng tái tạo bảo vệ môi trường',
      lessons: [
        {
          id: 'phy-g9-b15',
          lessonNumber: 15,
          title: 'Vòng năng lượng trên Trái Đất. Năng lượng hóa thạch',
          subtitle: 'Bài 16 SGK: Chu trình năng lượng, sự hình thành và cạn kiệt của nhiên liệu hóa thạch',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b15-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Vòng năng lượng & Năng lượng hóa thạch',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b15-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Nguồn gốc năng lượng & Nhiên liệu hóa thạch',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g9-b16',
          lessonNumber: 16,
          title: 'Một số dạng năng lượng tái tạo',
          subtitle: 'Bài 17 SGK: Năng lượng gió, mặt trời, thủy điện, sinh khối và lợi ích phát triển bền vững',
          ready: true,
          nodes: [
            {
              id: 'phy-g9-b16-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng tái tạo',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g9-b16-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Nhận biết và sử dụng năng lượng tái tạo',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g9-b16-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Năng lượng & Tốt nghiệp Vật lý 9',
              description: 'Thử thách tổng kết Unit 5 và Tốt nghiệp chương trình Vật lý THCS',
              type: 'checkpoint',
            },
            {
              id: 'phy-g9-b16-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Tốt nghiệp Vật lý 9',
              description: 'Phần thưởng vinh danh hoàn thành xuất sắc toàn bộ Vật lý lớp 9',
              type: 'chest',
            },
          ],
        },
      ],
    },
  ],
};
