import type { GradeCurriculum } from '../../curriculum/types';

export const GRADE_6_PHYSICS_CURRICULUM: GradeCurriculum = {
  grade: 6,
  title: 'Vật lý lớp 6 (Khoa học tự nhiên 6 - Kết nối tri thức)',
  chapters: [
    {
      id: 'phy-g6-c00',
      chapterNumber: 0,
      title: 'Unit 0 — Đo lường',
      description: 'Kỹ năng đo chiều dài, khối lượng, thời gian và nhiệt độ trong khoa học và đời sống',
      lessons: [
        {
          id: 'phy-g6-b01',
          lessonNumber: 1,
          title: 'Đo chiều dài',
          subtitle: 'Bài 5 SGK: Đơn vị, dụng cụ đo, giới hạn đo, độ chia nhỏ nhất và quy trình đo',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b01-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đo chiều dài',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b01-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đo chiều dài',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b02',
          lessonNumber: 2,
          title: 'Đo khối lượng',
          subtitle: 'Bài 6 SGK: Đơn vị khối lượng, các loại cân và kỹ năng đo chính xác',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b02-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đo khối lượng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b02-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đo khối lượng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b03',
          lessonNumber: 3,
          title: 'Đo thời gian',
          subtitle: 'Bài 7 SGK: Đơn vị giây, đồng hồ bấm giây và phương pháp đo khoảng thời gian',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b03-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đo thời gian',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b03-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đo thời gian',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b04',
          lessonNumber: 4,
          title: 'Đo nhiệt độ',
          subtitle: 'Bài 8 SGK: Thang nhiệt độ Celsius, các loại nhiệt kế và an toàn khi sử dụng',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b04-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đo nhiệt độ',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b04-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đo nhiệt độ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g6-b04-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy đo lường',
              description: 'Thử thách tổng kết Unit 0',
              type: 'checkpoint',
            },
            {
              id: 'phy-g6-b04-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 0',
              description: 'Phần thưởng hoàn thành Unit 0: Đo lường',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g6-c01',
      chapterNumber: 1,
      title: 'Unit 1 — Lực trong đời sống',
      description: 'Khái niệm lực, biểu diễn lực, lò xo, trọng lực, lực ma sát và lực cản của nước',
      lessons: [
        {
          id: 'phy-g6-b05',
          lessonNumber: 5,
          title: 'Lực là gì?',
          subtitle: 'Bài 40 SGK: Tác dụng của lực làm biến đổi chuyển động hoặc biến dạng vật',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b05-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Lực là gì?',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b05-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tác dụng của lực',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b06',
          lessonNumber: 6,
          title: 'Biểu diễn lực',
          subtitle: 'Bài 41 SGK: Gốc, phương, chiều và độ lớn của lực biểu diễn bằng mũi tên',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b06-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Biểu diễn lực',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b06-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Biểu diễn lực',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b07',
          lessonNumber: 7,
          title: 'Biến dạng của lò xo',
          subtitle: 'Bài 42 SGK: Độ dãn của lò xo treo thẳng đứng tỉ lệ với khối lượng vật treo',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b07-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Biến dạng lò xo',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b07-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Biến dạng lò xo',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b08',
          lessonNumber: 8,
          title: 'Trọng lực, lực hấp dẫn',
          subtitle: 'Bài 43 SGK: Trọng lực là lực hút của Trái Đất, phương thẳng đứng, chiều hướng về Trái Đất',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b08-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Trọng lực & Khối lượng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b08-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Trọng lực & Khối lượng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b09',
          lessonNumber: 9,
          title: 'Lực ma sát',
          subtitle: 'Bài 44 SGK: Ma sát trượt, ma sát nghỉ, lực cản và ứng dụng thực tế',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b09-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Lực ma sát',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b09-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Lực ma sát',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b10',
          lessonNumber: 10,
          title: 'Lực cản của nước',
          subtitle: 'Bài 45 SGK: Tác dụng cản trở chuyển động của nước và hình dạng khí động học',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b10-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Lực cản của nước',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b10-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Lực cản của nước',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g6-b10-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy cơ học',
              description: 'Thử thách tổng kết Unit 1',
              type: 'checkpoint',
            },
            {
              id: 'phy-g6-b10-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 1',
              description: 'Phần thưởng hoàn thành Unit 1: Lực trong đời sống',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g6-c02',
      chapterNumber: 2,
      title: 'Unit 2 — Năng lượng',
      description: 'Năng lượng, các dạng năng lượng, sự chuyển hóa, năng lượng hao phí và năng lượng tái tạo',
      lessons: [
        {
          id: 'phy-g6-b11',
          lessonNumber: 11,
          title: 'Năng lượng và sự truyền năng lượng',
          subtitle: 'Bài 46 SGK: Năng lượng đặc trưng cho khả năng tác dụng lực và truyền nhiệt',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b11-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng & Truyền năng lượng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b11-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Năng lượng & Truyền năng lượng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b12',
          lessonNumber: 12,
          title: 'Một số dạng năng lượng',
          subtitle: 'Bài 47 SGK: Động năng, thế năng, nhiệt năng, quang năng, hóa năng, điện năng',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b12-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Một số dạng năng lượng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b12-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Một số dạng năng lượng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b13',
          lessonNumber: 13,
          title: 'Sự chuyển hóa năng lượng',
          subtitle: 'Bài 48 SGK: Định luật bảo toàn năng lượng trong chuyển hóa và truyền năng lượng',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b13-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Sự chuyển hóa năng lượng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b13-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Sự chuyển hóa năng lượng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b14',
          lessonNumber: 14,
          title: 'Năng lượng hao phí',
          subtitle: 'Bài 49 SGK: Năng lượng có ích và năng lượng hao phí dưới dạng nhiệt',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b14-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng hao phí',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b14-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Năng lượng hao phí',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b15',
          lessonNumber: 15,
          title: 'Năng lượng tái tạo',
          subtitle: 'Bài 50 SGK: Năng lượng Mặt Trời, năng lượng gió, thủy điện và nhiên liệu sinh học',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b15-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng tái tạo',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b15-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Năng lượng tái tạo',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b16',
          lessonNumber: 16,
          title: 'Tiết kiệm năng lượng',
          subtitle: 'Bài 51 SGK: Các biện pháp sử dụng năng lượng hiệu quả và bảo vệ môi trường',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b16-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Tiết kiệm năng lượng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b16-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tiết kiệm năng lượng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g6-b16-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy năng lượng',
              description: 'Thử thách tổng kết Unit 2',
              type: 'checkpoint',
            },
            {
              id: 'phy-g6-b16-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 2',
              description: 'Phần thưởng hoàn thành Unit 2: Năng lượng',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g6-c03',
      chapterNumber: 3,
      title: 'Unit 3 — Trái Đất và bầu trời',
      description: 'Chuyển động nhìn thấy của Mặt Trời, các pha của Mặt Trăng, Hệ Mặt Trời và Ngân hà',
      lessons: [
        {
          id: 'phy-g6-b17',
          lessonNumber: 17,
          title: 'Chuyển động nhìn thấy của Mặt Trời. Thiên thể',
          subtitle: 'Bài 52 SGK: Mặt Trời mọc ở hướng đông, lặn ở hướng tây và chuyển động tự quay của Trái Đất',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b17-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Chuyển động nhìn thấy Mặt Trời',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b17-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Chuyển động Mặt Trời & Thiên thể',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b18',
          lessonNumber: 18,
          title: 'Mặt Trăng',
          subtitle: 'Bài 53 SGK: Các hình dạng nhìn thấy của Mặt Trăng (pha Mặt Trăng) từ Trái Đất',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b18-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Mặt Trăng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b18-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Mặt Trăng & Tuần trăng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b19',
          lessonNumber: 19,
          title: 'Hệ Mặt Trời',
          subtitle: 'Bài 54 SGK: Mặt Trời và 8 hành tinh trong Hệ Mặt Trời theo thứ tự khoảng cách',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b19-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Hệ Mặt Trời',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b19-n01',
              nodeIndex: 2,
              title: 'Luyện tập: 8 Hành tinh Hệ Mặt Trời',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g6-b20',
          lessonNumber: 20,
          title: 'Ngân hà',
          subtitle: 'Bài 55 SGK: Dải Ngân hà (Milky Way), cấu trúc xoắn ốc và vị trí của Hệ Mặt Trời',
          ready: true,
          nodes: [
            {
              id: 'phy-g6-b20-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Dải Ngân hà',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g6-b20-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Dải Ngân hà & Vũ trụ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g6-b20-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy thiên văn',
              description: 'Thử thách tổng kết Unit 3 & Toàn khóa Vật lý 6',
              type: 'checkpoint',
            },
            {
              id: 'phy-g6-b20-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Toàn khóa Vật lý 6',
              description: 'Phần thưởng vinh danh hoàn thành xuất sắc toàn bộ 20 bài Vật lý lớp 6!',
              type: 'chest',
            },
          ],
        },
      ],
    },
  ],
};
