import type { GradeCurriculum } from '../../curriculum/types';

export const GRADE_8_PHYSICS_CURRICULUM: GradeCurriculum = {
  grade: 8,
  title: 'Vật lý lớp 8 (Khoa học tự nhiên 8 - Kết nối tri thức)',
  chapters: [
    {
      id: 'phy-g8-c01',
      chapterNumber: 1,
      title: 'Unit 1 — Khối lượng riêng và áp suất',
      description: 'Khối lượng riêng, phương pháp đo thực hành, áp suất chất rắn, áp suất chất lỏng, áp suất khí quyển và lực đẩy Archimedes',
      lessons: [
        {
          id: 'phy-g8-b01',
          lessonNumber: 1,
          title: 'Khối lượng riêng',
          subtitle: 'Bài 13 SGK: Định nghĩa, công thức D = m / V và đơn vị đo khối lượng riêng (kg/m³, g/cm³)',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b01-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Khối lượng riêng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b01-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính khối lượng riêng D = m / V',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b02',
          lessonNumber: 2,
          title: 'Thực hành xác định khối lượng riêng',
          subtitle: 'Bài 14 SGK: Quy trình đo khối lượng riêng của vật rắn hình dạng học và hình dạng bất kì',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b02-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Kĩ năng thực hành đo khối lượng riêng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b02-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Phương pháp cân & đo thể tích',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b03',
          lessonNumber: 3,
          title: 'Áp suất trên một bề mặt',
          subtitle: 'Bài 15 SGK: Áp lực, áp suất p = F / S, đơn vị Pascal (Pa) và các biện pháp tăng/giảm áp suất',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b03-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Áp suất trên một bề mặt',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b03-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính áp suất p = F / S',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b04',
          lessonNumber: 4,
          title: 'Áp suất chất lỏng. Áp suất khí quyển',
          subtitle: 'Bài 16 SGK: Áp suất do cột chất lỏng gây ra, bình thông nhau và hiện tượng áp suất khí quyển',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b04-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Áp suất chất lỏng & Áp suất khí quyển',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b04-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Áp suất cột chất lỏng & Khí quyển',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b05',
          lessonNumber: 5,
          title: 'Lực đẩy Archimedes',
          subtitle: 'Bài 17 SGK: Độ lớn lực đẩy Archimedes F_A = d . V, điều kiện vật chìm, vật nổi, lơ lửng',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b05-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Lực đẩy Archimedes',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b05-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Tính lực đẩy Archimedes & Vật nổi/chìm',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g8-b05-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Cơ học & Áp suất',
              description: 'Thử thách tổng kết Unit 1: Khối lượng riêng & Áp suất',
              type: 'checkpoint',
            },
            {
              id: 'phy-g8-b05-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 1: Cơ học & Áp suất',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 1',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g8-c02',
      chapterNumber: 2,
      title: 'Unit 2 — Tác dụng làm quay của lực',
      description: 'Lực tác dụng làm quay quanh một trục cố định, momen lực, quy tắc cân bằng và ứng dụng đòn bẩy',
      lessons: [
        {
          id: 'phy-g8-b06',
          lessonNumber: 6,
          title: 'Tác dụng làm quay của lực. Moment lực',
          subtitle: 'Bài 18 SGK: Trục quay, cánh tay đòn, moment lực và tác dụng làm quay vật',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b06-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Moment lực',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b06-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Xác định moment lực & Tác dụng quay',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b07',
          lessonNumber: 7,
          title: 'Đòn bẩy và ứng dụng',
          subtitle: 'Bài 19 SGK: Điểm tựa, cánh tay đòn của đòn bẩy và các ứng dụng thực tế trong đời sống kĩ thuật',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b07-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Đòn bẩy và ứng dụng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b07-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Phân tích các loại đòn bẩy',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g8-b07-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Đòn bẩy & Moment lực',
              description: 'Thử thách tổng kết Unit 2: Tác dụng làm quay của lực',
              type: 'checkpoint',
            },
            {
              id: 'phy-g8-b07-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 2: Moment & Đòn bẩy',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 2',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g8-c03',
      chapterNumber: 3,
      title: 'Unit 3 — Điện',
      description: 'Hiện tượng nhiễm điện do cọ xát, dòng điện, nguồn điện, mạch điện, tác dụng của dòng điện, cường độ dòng điện và hiệu điện thế',
      lessons: [
        {
          id: 'phy-g8-b08',
          lessonNumber: 8,
          title: 'Hiện tượng nhiễm điện do cọ xát',
          subtitle: 'Bài 20 SGK: Sự nhiễm điện, hai loại điện tích (+/-) và tương tác hút/đẩy giữa các điện tích',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b08-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Nhiễm điện do cọ xát',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b08-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Hai loại điện tích & Tương tác',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b09',
          lessonNumber: 9,
          title: 'Dòng điện, nguồn điện',
          subtitle: 'Bài 21 SGK: Bản chất dòng điện trong kim loại, các loại nguồn điện và hai cực của nguồn',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b09-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Dòng điện, nguồn điện',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b09-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Bản chất dòng điện & Cực nguồn điện',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b10',
          lessonNumber: 10,
          title: 'Mạch điện đơn giản',
          subtitle: 'Bài 22 SGK: Kí hiệu quy ước các bộ phận mạch điện, sơ đồ mạch điện và chiều dòng điện',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b10-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Mạch điện đơn giản',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b10-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đọc và vẽ sơ đồ mạch điện',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b11',
          lessonNumber: 11,
          title: 'Tác dụng của dòng điện',
          subtitle: 'Bài 23 SGK: Tác dụng nhiệt, phát sáng, từ, hóa học và sinh lí của dòng điện',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b11-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Các tác dụng của dòng điện',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b11-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Nhận biết tác dụng của dòng điện',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b12',
          lessonNumber: 12,
          title: 'Cường độ dòng điện và hiệu điện thế',
          subtitle: 'Bài 24 SGK: Định nghĩa, đơn vị ampe (A), vôn (V), ampe kế mắc nối tiếp, vôn kế mắc song song',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b12-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Cường độ dòng điện & Hiệu điện thế',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b12-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đo và tính cường độ I & Hiệu điện thế U',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b13',
          lessonNumber: 13,
          title: 'Thực hành đo cường độ dòng điện và hiệu điện thế',
          subtitle: 'Bài 25 SGK: Quy trình mắc ampe kế, vôn kế vào mạch điện, đọc thang đo và xử lý số liệu',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b13-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Kĩ năng thực hành đo I và U',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b13-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Kĩ năng mắc mạch & Đọc dụng cụ đo',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g8-b13-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Điện học Lớp 8',
              description: 'Thử thách tổng kết Unit 3: Điện',
              type: 'checkpoint',
            },
            {
              id: 'phy-g8-b13-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 3: Điện',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 3',
              type: 'chest',
            },
          ],
        },
      ],
    },
    {
      id: 'phy-g8-c04',
      chapterNumber: 4,
      title: 'Unit 4 — Nhiệt',
      description: 'Năng lượng nhiệt, nội năng, thực hành đo joulemeter, các hình thức truyền nhiệt và hiện tượng nở vì nhiệt',
      lessons: [
        {
          id: 'phy-g8-b14',
          lessonNumber: 14,
          title: 'Năng lượng nhiệt và nội năng',
          subtitle: 'Bài 26 SGK: Mô hình phân tử, nhiệt năng, nội năng và các cách làm thay đổi nội năng của vật',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b14-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Năng lượng nhiệt và nội năng',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b14-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Phân biệt nhiệt năng & Nội năng',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b15',
          lessonNumber: 15,
          title: 'Thực hành đo năng lượng nhiệt bằng joulemeter',
          subtitle: 'Bài 27 SGK: Sử dụng oát kế/joulemeter để đo năng lượng nhiệt cung cấp cho khối chất lỏng',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b15-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Thực hành đo năng lượng nhiệt',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b15-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Đo năng lượng nhiệt bằng joulemeter',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b16',
          lessonNumber: 16,
          title: 'Sự truyền nhiệt',
          subtitle: 'Bài 28 SGK: Dẫn nhiệt, đối lưu, bức xạ nhiệt và ứng dụng thực tế trong đời sống (phích nước, nhà kính)',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b16-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Ba hình thức truyền nhiệt',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b16-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Phân biệt dẫn nhiệt, đối lưu, bức xạ',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
          ],
        },
        {
          id: 'phy-g8-b17',
          lessonNumber: 17,
          title: 'Sự nở vì nhiệt',
          subtitle: 'Bài 29 SGK: Sự nở vì nhiệt của chất rắn, lỏng, khí và ứng dụng kĩ thuật (băng kép, ray tàu hỏa)',
          ready: true,
          nodes: [
            {
              id: 'phy-g8-b17-theory',
              nodeIndex: 1,
              title: 'Lý thuyết: Sự nở vì nhiệt',
              description: '2 phút ghi nhớ',
              type: 'theory',
            },
            {
              id: 'phy-g8-b17-n01',
              nodeIndex: 2,
              title: 'Luyện tập: Ứng dụng sự nở vì nhiệt trong đời sống',
              description: '6 câu hỏi thực hành',
              type: 'lesson',
            },
            {
              id: 'phy-g8-b17-boss',
              nodeIndex: 3,
              title: 'Thử thách: Bậc thầy Nhiệt học Lớp 8',
              description: 'Thử thách tổng kết Unit 4: Nhiệt học',
              type: 'checkpoint',
            },
            {
              id: 'phy-g8-b17-chest',
              nodeIndex: 4,
              title: 'Rương kho báu Unit 4: Nhiệt học',
              description: 'Phần thưởng hoàn thành xuất sắc Unit 4',
              type: 'chest',
            },
          ],
        },
      ],
    },
  ],
};
