export interface Skill {
  id: string;
  name: string;
  grade: 6 | 7 | 8 | 9;
  lessonId: string;
  category: 'ly-thuyet' | 'tinh-toan' | 'phuong-trinh' | 'nhan-biet' | 'thi-nghiem';
  description: string;
}

export const SKILLS: Skill[] = [
  // LỚP 6
  {
    id: 'matter-diversity',
    name: 'Vật thể và chất',
    grade: 6,
    lessonId: 'g6-b09',
    category: 'ly-thuyet',
    description: 'Phân biệt vật thể tự nhiên và nhân tạo, vật sống và không sống; một vật thể gồm nhiều chất và một chất tạo nên nhiều vật thể.',
  },
  {
    id: 'physical-chemical-properties',
    name: 'Tính chất vật lí & hóa học',
    grade: 6,
    lessonId: 'g6-b09',
    category: 'ly-thuyet',
    description: 'Nhận biết các tính chất vật lí (màu, mùi, vị, thể, tan, nóng chảy, sôi) và tính chất hóa học (cháy, gỉ sét).',
  },
  {
    id: 'matter-changes',
    name: 'Biến đổi vật lí & hóa học',
    grade: 6,
    lessonId: 'g6-b09',
    category: 'nhan-biet',
    description: 'Phân biệt hiện tượng biến đổi vật lí (không tạo chất mới) và biến đổi hóa học (tạo ra chất mới).',
  },
  {
    id: 'states-of-matter',
    name: 'Ba thể của chất & Mô hình hạt',
    grade: 6,
    lessonId: 'g6-b10',
    category: 'ly-thuyet',
    description: 'Đặc điểm hình dạng, thể tích và khả năng nén của thể rắn, lỏng, khí cùng mô hình chuyển động của hạt.',
  },
  {
    id: 'state-changes',
    name: 'Sự chuyển thể của chất',
    grade: 6,
    lessonId: 'g6-b10',
    category: 'ly-thuyet',
    description: 'Các quá trình nóng chảy, đông đặc, bay hơi, ngưng tụ và sự giữ nguyên nhiệt độ khi chuyển thể.',
  },
  {
    id: 'boiling-and-graphs',
    name: 'Sự sôi & Các yếu tố bay hơi',
    grade: 6,
    lessonId: 'g6-b10',
    category: 'thi-nghiem',
    description: 'Nhiệt độ sôi của chất lỏng, các yếu tố ảnh hưởng tốc độ bay hơi (nhiệt độ, gió, diện tích mặt thoáng) và đọc đồ thị.',
  },
  {
    id: 'oxygen-role',
    name: 'Tính chất & Vai trò của Oxygen',
    grade: 6,
    lessonId: 'g6-b11',
    category: 'ly-thuyet',
    description: 'Tính chất vật lí của khí oxygen, vai trò duy trì sự cháy và sự sống (hô hấp).',
  },
  {
    id: 'air-and-environment',
    name: 'Thành phần không khí & Môi trường',
    grade: 6,
    lessonId: 'g6-b11',
    category: 'thi-nghiem',
    description: 'Tỉ lệ thành phần các khí trong không khí (nitrogen 78%, oxygen 21%), thí nghiệm úp cốc đốt nến và biện pháp giảm ô nhiễm không khí.',
  },

  // LỚP 7
  {
    id: 'science-method',
    name: 'Phương pháp & kĩ năng KHTN',
    grade: 7,
    lessonId: 'g7-b01',
    category: 'thi-nghiem',
    description: 'Trình tự phương pháp khoa học, kĩ năng quan sát, sử dụng dụng cụ và quy tắc an toàn phòng thí nghiệm.',
  },
  {
    id: 'atom-structure',
    name: 'Cấu tạo nguyên tử',
    grade: 7,
    lessonId: 'g7-b02',
    category: 'ly-thuyet',
    description: 'Xác định số hạt proton, neutron, electron trong nguyên tử và điện tích hạt nhân.',
  },
  {
    id: 'atomic-mass',
    name: 'Khối lượng nguyên tử (amu)',
    grade: 7,
    lessonId: 'g7-b02',
    category: 'tinh-toan',
    description: 'Tính khối lượng nguyên tử theo đơn vị amu dựa trên số hạt p và n.',
  },
  {
    id: 'chemical-element',
    name: 'Nguyên tố hóa học',
    grade: 7,
    lessonId: 'g7-b03',
    category: 'ly-thuyet',
    description: 'Kí hiệu hóa học, tên gọi theo IUPAC và số hiệu nguyên tử Z.',
  },
  {
    id: 'periodic-table-structure',
    name: 'Cấu tạo bảng tuần hoàn',
    grade: 7,
    lessonId: 'g7-b04',
    category: 'ly-thuyet',
    description: 'Ý nghĩa của ô nguyên tố, chu kì và nhóm (A, B) trong bảng tuần hoàn.',
  },

  // LỚP 8
  {
    id: 'chemical-change',
    name: 'Dấu hiệu phản ứng hóa học',
    grade: 8,
    lessonId: 'g8-b02',
    category: 'nhan-biet',
    description: 'Nhận biết biến đổi hóa học qua sự đổi màu, kết tủa, tỏa nhiệt, sinh chất khí.',
  },
  {
    id: 'mol-definition',
    name: 'Khái niệm Mol & Số Avogadro',
    grade: 8,
    lessonId: 'g8-b03',
    category: 'ly-thuyet',
    description: 'Hiểu mol là lượng chất chứa 6,022 × 10^23 nguyên tử hoặc phân tử.',
  },
  {
    id: 'mol-mass-calc',
    name: 'Chuyển đổi Mol và Khối lượng',
    grade: 8,
    lessonId: 'g8-b03',
    category: 'tinh-toan',
    description: 'Áp dụng công thức m = n × M và n = m / M.',
  },
  {
    id: 'gas-volume-calc',
    name: 'Thể tích khí ở ĐKC (25 °C, 1 bar)',
    grade: 8,
    lessonId: 'g8-b03',
    category: 'tinh-toan',
    description: 'Tính thể tích chất khí V = n × 24,79 L và ngược lại.',
  },
  {
    id: 'gas-density-calc',
    name: 'Tỉ khối chất khí',
    grade: 8,
    lessonId: 'g8-b03',
    category: 'tinh-toan',
    description: 'Xác định chất khí nặng hay nhẹ hơn khí khác hoặc so với không khí (M = 29).',
  },
  {
    id: 'mass-percentage-calc',
    name: 'Nồng độ phần trăm C%',
    grade: 8,
    lessonId: 'g8-b04',
    category: 'tinh-toan',
    description: 'Tính C% = (m_ct / m_dd) × 100% và khối lượng chất tan, dung môi.',
  },
  {
    id: 'molar-concentration-calc',
    name: 'Nồng độ mol CM',
    grade: 8,
    lessonId: 'g8-b04',
    category: 'tinh-toan',
    description: 'Tính CM = n / V (lít) và pha chế dung dịch.',
  },
  {
    id: 'mass-conservation',
    name: 'Định luật bảo toàn khối lượng',
    grade: 8,
    lessonId: 'g8-b05',
    category: 'tinh-toan',
    description: 'Áp dụng tổng khối lượng chất tham gia bằng tổng khối lượng chất sản phẩm.',
  },
  {
    id: 'balance-equation',
    name: 'Lập và cân bằng PTHH',
    grade: 8,
    lessonId: 'g8-b05',
    category: 'phuong-trinh',
    description: 'Tìm hệ số nguyên tối giản cân bằng số nguyên tử mỗi nguyên tố hai vế.',
  },
  {
    id: 'stoichiometry-calc',
    name: 'Tính theo phương trình hóa học',
    grade: 8,
    lessonId: 'g8-b06',
    category: 'tinh-toan',
    description: 'Tính lượng chất sản phẩm hoặc tham gia dựa trên tỉ lệ mol của PTHH.',
  },
  {
    id: 'reaction-rate',
    name: 'Tốc độ phản ứng & Xúc tác',
    grade: 8,
    lessonId: 'g8-b07',
    category: 'thi-nghiem',
    description: 'Ảnh hưởng của nồng độ, nhiệt độ, diện tích tiếp xúc và chất xúc tác.',
  },
  {
    id: 'acid-properties',
    name: 'Tính chất hóa học của Acid',
    grade: 8,
    lessonId: 'g8-b08',
    category: 'phuong-trinh',
    description: 'Đổi màu chỉ thị, tác dụng với kim loại đứng trước H, oxide bazơ và base.',
  },
  {
    id: 'base-properties',
    name: 'Tính chất hóa học của Base',
    grade: 8,
    lessonId: 'g8-b09',
    category: 'phuong-trinh',
    description: 'Kiềm làm xanh quỳ tím, hồng phenolphtalein; tác dụng với acid, oxide axit.',
  },
  {
    id: 'ph-scale',
    name: 'Thang pH và Môi trường dung dịch',
    grade: 8,
    lessonId: 'g8-b09',
    category: 'nhan-biet',
    description: 'Nhận biết môi trường axit (pH < 7), trung tính (pH = 7), bazơ (pH > 7).',
  },
  {
    id: 'oxide-classification',
    name: 'Phân loại & Tính chất của Oxide',
    grade: 8,
    lessonId: 'g8-b10',
    category: 'ly-thuyet',
    description: 'Phân loại oxide axit, oxide bazơ, oxide lưỡng tính và oxide trung tính.',
  },
  {
    id: 'salt-reactions',
    name: 'Tính chất & Điều kiện phản ứng Muối',
    grade: 8,
    lessonId: 'g8-b11',
    category: 'phuong-trinh',
    description: 'Phản ứng trao đổi trong dung dịch sinh kết tủa, khí hoặc nước.',
  },
  {
    id: 'fertilizer-classification',
    name: 'Phân loại Phân bón hóa học',
    grade: 8,
    lessonId: 'g8-b12',
    category: 'ly-thuyet',
    description: 'Phân biệt phân đạm (N), phân lân (P), phân kali (K) và phân hỗn hợp NPK.',
  },
  {
    id: 'fertilizer-calc',
    name: 'Hàm lượng dinh dưỡng phân bón',
    grade: 8,
    lessonId: 'g8-b12',
    category: 'tinh-toan',
    description: 'Tính toán phần trăm khối lượng nguyên tố dinh dưỡng trong phân bón.',
  },

  // LỚP 9
  {
    id: 'metal-properties',
    name: 'Tính chất chung của Kim loại',
    grade: 9,
    lessonId: 'g9-b18',
    category: 'ly-thuyet',
    description: 'Ánh kim, dẫn điện, dẫn nhiệt, tính dẻo và phản ứng với phi kim, axit, muối.',
  },
  {
    id: 'activity-series',
    name: 'Dãy hoạt động hóa học của Kim loại',
    grade: 9,
    lessonId: 'g9-b19',
    category: 'phuong-trinh',
    description: 'So sánh mức độ hoạt động và khả năng đẩy kim loại yếu hơn ra khỏi muối.',
  },
  {
    id: 'metal-extraction',
    name: 'Tách kim loại & Hợp kim',
    grade: 9,
    lessonId: 'g9-b20',
    category: 'thi-nghiem',
    description: 'Phương pháp nhiệt luyện, điện phân và sản xuất gang, thép.',
  },
  {
    id: 'metal-vs-nonmetal',
    name: 'Kim loại vs Phi kim',
    grade: 9,
    lessonId: 'g9-b21',
    category: 'ly-thuyet',
    description: 'So sánh tính chất vật lí, hóa học và ứng dụng của kim loại và phi kim.',
  },
  {
    id: 'organic-intro',
    name: 'Khái niệm Hợp chất hữu cơ',
    grade: 9,
    lessonId: 'g9-b22',
    category: 'ly-thuyet',
    description: 'Phân biệt hợp chất hữu cơ và vô cơ; hydrocarbon và dẫn xuất.',
  },
  {
    id: 'alkane-methane',
    name: 'Alkane & Methane',
    grade: 9,
    lessonId: 'g9-b23',
    category: 'phuong-trinh',
    description: 'Công thức chung alkane, phản ứng cháy tỏa nhiệt và phản ứng thế halogen.',
  },
  {
    id: 'alkene-ethylene',
    name: 'Alkene & Ethylene',
    grade: 9,
    lessonId: 'g9-b24',
    category: 'nhan-biet',
    description: 'Liên kết đôi C=C, phản ứng cộng làm mất màu dung dịch brom (Br2).',
  },
  {
    id: 'fuel-sources',
    name: 'Nguồn nhiên liệu hóa thạch',
    grade: 9,
    lessonId: 'g9-b25',
    category: 'ly-thuyet',
    description: 'Dầu mỏ, khí thiên nhiên, than đá và sử dụng năng lượng bền vững.',
  },
  {
    id: 'alcohol-properties',
    name: 'Ethylic alcohol (Rượu etylic)',
    grade: 9,
    lessonId: 'g9-b26',
    category: 'phuong-trinh',
    description: 'Cấu tạo nhóm -OH, phản ứng với Na, phản ứng cháy và độ rượu.',
  },
  {
    id: 'acetic-acid-properties',
    name: 'Acetic acid (Axit axetic)',
    grade: 9,
    lessonId: 'g9-b27',
    category: 'phuong-trinh',
    description: 'Tính axit của nhóm -COOH và phản ứng este hóa với rượu etylic.',
  },
  {
    id: 'lipid-fats',
    name: 'Lipid & Chất béo',
    grade: 9,
    lessonId: 'g9-b28',
    category: 'ly-thuyet',
    description: 'Thành phần este của glycerol với axit béo, phản ứng xà phòng hóa.',
  },
  {
    id: 'carbohydrate-identification',
    name: 'Nhận biết Glucose & Saccharose',
    grade: 9,
    lessonId: 'g9-b29',
    category: 'nhan-biet',
    description: 'Phản ứng tráng bạc của glucose, phân biệt đường đơn và đường đôi.',
  },
  {
    id: 'starch-cellulose',
    name: 'Tinh bột & Cellulose',
    grade: 9,
    lessonId: 'g9-b30',
    category: 'nhan-biet',
    description: 'Phản ứng màu với iodine, phản ứng thủy phân tạo glucose.',
  },
  {
    id: 'protein-structure',
    name: 'Protein',
    grade: 9,
    lessonId: 'g9-b31',
    category: 'ly-thuyet',
    description: 'Thành phần amino acid, sự đông tụ bởi nhiệt độ và axit/kiềm.',
  },
  {
    id: 'polymer-applications',
    name: 'Polymer & Vật liệu nhân tạo',
    grade: 9,
    lessonId: 'g9-b32',
    category: 'ly-thuyet',
    description: 'Khái niệm mắt xích, chất dẻo (PE, PVC), tơ sợi và cao su.',
  },
  {
    id: 'earth-crust-chemistry',
    name: 'Hóa học vỏ Trái Đất',
    grade: 9,
    lessonId: 'g9-b33',
    category: 'ly-thuyet',
    description: 'Thành phần khoáng sản, quặng kim loại và khai thác tài nguyên.',
  },
  {
    id: 'limestone-silicate',
    name: 'Khai thác đá vôi & Silicate',
    grade: 9,
    lessonId: 'g9-b34',
    category: 'thi-nghiem',
    description: 'Nhiệt phân đá vôi thành vôi sống (CaO), sản xuất xi măng và thủy tinh.',
  },
  {
    id: 'carbon-cycle-environment',
    name: 'Chu trình Carbon & Môi trường',
    grade: 9,
    lessonId: 'g9-b35',
    category: 'ly-thuyet',
    description: 'Chu trình tuần hoàn carbon, hiệu ứng nhà kính và biến đổi khí hậu.',
  },
  // SINH HỌC LỚP 6
  {
    id: 'bio-kinh-lup',
    name: 'Kỹ năng sử dụng kính lúp',
    grade: 6,
    lessonId: 'bio-g6-b01',
    category: 'thi-nghiem',
    description: 'Nhận biết cấu tạo, thao tác quan sát mẫu vật nhỏ và quy tắc bảo quản kính lúp.',
  },
  {
    id: 'bio-kinh-hien-vi',
    name: 'Kỹ năng sử dụng kính hiển vi quang học',
    grade: 6,
    lessonId: 'bio-g6-b02',
    category: 'thi-nghiem',
    description: 'Thành thạo cấu tạo 4 hệ thống, 3 bước lấy sáng và lấy nét quan sát tế bào trên kính hiển vi quang học.',
  },
  {
    id: 'bio-te-bao-co-ban',
    name: 'Tế bào – Đơn vị cơ bản của sự sống',
    grade: 6,
    lessonId: 'bio-g6-b03',
    category: 'ly-thuyet',
    description: 'Nhận biết kích thước hiển vi, các tế bào lớn quan sát được và sự đa dạng hình dạng tế bào.',
  },
  {
    id: 'bio-cau-tao-te-bao',
    name: 'Cấu tạo và chức năng tế bào',
    grade: 6,
    lessonId: 'bio-g6-b04',
    category: 'ly-thuyet',
    description: 'Phân tích 3 thành phần cơ bản của tế bào; phân biệt tế bào nhân sơ vs nhân thực, tế bào thực vật vs động vật.',
  },
  {
    id: 'bio-sinh-san-te-bao',
    name: 'Sự lớn lên và sinh sản của tế bào',
    grade: 6,
    lessonId: 'bio-g6-b05',
    category: 'tinh-toan',
    description: 'Hiểu cơ chế nhân phân chia trước, chất tế bào phân chia sau; vận dụng công thức tính số tế bào con N = a × 2^n.',
  },
  {
    id: 'bio-thuc-hanh-te-bao',
    name: 'Thực hành quan sát tế bào',
    grade: 6,
    lessonId: 'bio-g6-b06',
    category: 'thi-nghiem',
    description: 'Quy trình làm tiêu bản tế bào biểu bì vảy hành và thịt quả cà chua chín; đối chiếu đặc điểm hình dạng dưới kính hiển vi.',
  },
  {
    id: 'bio-co-the-sinh-vat',
    name: 'Cơ thể sinh vật & Sinh vật đơn bào - đa bào',
    grade: 6,
    lessonId: 'bio-g6-b07',
    category: 'ly-thuyet',
    description: 'Nhận biết 6 dấu hiệu của sự sống; phân biệt sinh vật đơn bào và sinh vật đa bào kèm các đại diện tiêu biểu.',
  },
  {
    id: 'bio-to-chuc-da-bao',
    name: 'Tổ chức cơ thể đa bào',
    grade: 6,
    lessonId: 'bio-g6-b08',
    category: 'ly-thuyet',
    description: 'Nắm vững chuỗi cấp độ tổ chức sống: Tế bào → Mô → Cơ quan → Hệ cơ quan → Cơ thể; các loại mô và hệ cơ quan ở thực vật và động vật.',
  },
  {
    id: 'bio-thuc-hanh-co-the',
    name: 'Thực hành quan sát đơn bào và đa bào',
    grade: 6,
    lessonId: 'bio-g6-b09',
    category: 'thi-nghiem',
    description: 'Quan sát trùng roi, trùng giày trong nước rơm bằng kính hiển vi; xác định vị trí cơ quan trên mô hình cơ thể người và cây xanh.',
  },
  {
    id: 'bio-he-thong-phan-loai',
    name: 'Hệ thống phân loại sinh vật & 7 bậc phân loại',
    grade: 6,
    lessonId: 'bio-g6-b10',
    category: 'ly-thuyet',
    description: 'Thứ bậc 7 cấp độ phân loại từ Loài đến Giới; hệ thống 5 giới (Whittaker) và cách gọi tên khoa học của loài.',
  },
  {
    id: 'bio-khoa-luong-phan',
    name: 'Phương pháp khóa lưỡng phân',
    grade: 6,
    lessonId: 'bio-g6-b11',
    category: 'ly-thuyet',
    description: 'Nguyên tắc chia nhánh dựa trên các cặp đặc điểm đối lập để nhận diện và định danh sinh vật.',
  },
  {
    id: 'bio-vi-khuan',
    name: 'Hình thái & vai trò của vi khuẩn',
    grade: 6,
    lessonId: 'bio-g6-b12',
    category: 'ly-thuyet',
    description: 'Cấu tạo tế bào nhân sơ; các dạng hình que, cầu, xoắn, phẩy; vai trò lên men có ích và các bệnh truyền nhiễm.',
  },
  {
    id: 'bio-thuc-hanh-sua-chua',
    name: 'Thực hành làm sữa chua & lên men',
    grade: 6,
    lessonId: 'bio-g6-b13',
    category: 'thi-nghiem',
    description: 'Kỹ thuật lên men sữa chua nhờ vi khuẩn lactic ở nhiệt độ ủ ấm tối ưu và quan sát vi khuẩn dưới kính hiển vi.',
  },
  {
    id: 'bio-virus',
    name: 'Cấu tạo & phòng bệnh do virus',
    grade: 6,
    lessonId: 'bio-g6-b14',
    category: 'ly-thuyet',
    description: 'Cấu tạo hạt virus vỏ protein bọc lõi acid nucleic; tính ký sinh nội bào bắt buộc và vai trò của vaccine.',
  },
  {
    id: 'bio-nguyen-sinh-vat',
    name: 'Nhận diện & vai trò nguyên sinh vật',
    grade: 6,
    lessonId: 'bio-g6-b15',
    category: 'ly-thuyet',
    description: 'Đặc điểm sinh vật nhân thực đơn bào; vai trò sinh thái và phòng tránh bệnh sốt rét, kiết lị.',
  },
  {
    id: 'bio-thuc-hanh-nguyen-sinh-vat',
    name: 'Thực hành soi nguyên sinh vật',
    grade: 6,
    lessonId: 'bio-g6-b16',
    category: 'thi-nghiem',
    description: 'Làm tiêu bản giọt nước ao hồ; quan sát cấu tạo và kiểu bơi của trùng roi, trùng giày, tảo silic.',
  },
  {
    id: 'bio-gioi-nam',
    name: 'Đặc điểm & phân loại giới Nấm',
    grade: 6,
    lessonId: 'bio-g6-b17',
    category: 'ly-thuyet',
    description: 'Đặc điểm nhân thực dị dưỡng, thành chitin; phân loại nấm men, nấm mốc, nấm thể quả và cách nhận diện nấm độc.',
  },
  {
    id: 'bio-thuc-hanh-nam',
    name: 'Thực hành quan sát các loại nấm',
    grade: 6,
    lessonId: 'bio-g6-b18',
    category: 'thi-nghiem',
    description: 'Quan sát nấm mốc bánh mì và cấu tạo nấm rơm thể quả (mũ, phiến, cuống, bao gốc); phân biệt với nấm độc.',
  },
  {
    id: 'bio-thuc-vat-4-nganh',
    name: '4 ngành thực vật & sơ đồ tiến hóa',
    grade: 6,
    lessonId: 'bio-g6-b19',
    category: 'ly-thuyet',
    description: 'Đặc điểm tiến hóa từ Rêu (chưa có mạch) → Dương xỉ (có mạch, bào tử) → Hạt trần (nón hở) → Hạt kín (có hoa và quả).',
  },
  {
    id: 'bio-thuc-hanh-thuc-vat',
    name: 'Phân biệt các nhóm thực vật',
    grade: 6,
    lessonId: 'bio-g6-b20',
    category: 'thi-nghiem',
    description: 'Nhận diện rễ giả và túi bào tử rêu, ổ túi bào tử dương xỉ, nón thông và hoa quả hạt kín.',
  },
  {
    id: 'bio-gioi-dong-vat',
    name: 'Động vật không xương sống & có xương sống',
    grade: 6,
    lessonId: 'bio-g6-b21',
    category: 'ly-thuyet',
    description: 'Đặc điểm 4 nhóm không xương sống (ruột khoang, giun, thân mềm, chân khớp) và 5 lớp có xương sống (cá, lưỡng cư, bò sát, chim, thú).',
  },
  {
    id: 'bio-thuc-hanh-dong-vat',
    name: 'Thực hành quan sát động vật',
    grade: 6,
    lessonId: 'bio-g6-b22',
    category: 'thi-nghiem',
    description: 'Kỹ năng quan sát tập tính di chuyển, cơ quan vận động và môi trường sống của các loài động vật.',
  },
  {
    id: 'bio-da-dang-sinh-hoc',
    name: 'Đa dạng sinh học & biện pháp bảo tồn',
    grade: 6,
    lessonId: 'bio-g6-b23',
    category: 'ly-thuyet',
    description: 'Khái niệm, vai trò, nguyên nhân suy giảm và các biện pháp bảo tồn đa dạng sinh học, vườn quốc gia, Sách Đỏ.',
  },
  {
    id: 'bio-khao-sat-ngoai-thien-nhien',
    name: 'Kỹ năng khảo sát sinh vật thực địa',
    grade: 6,
    lessonId: 'bio-g6-b24',
    category: 'thi-nghiem',
    description: 'Kỹ năng điều tra thực địa, sử dụng dụng cụ nghiên cứu và nguyên tắc ứng xử văn minh bảo vệ môi trường sinh thái.',
  },

  // SINH HỌC LỚP 7 (KHTN 7 - KẾT NỐI TRI THỨC)
  {
    id: 'bio-trao-doi-chat-nang-luong',
    name: 'Khái quát trao đổi chất & Chuyển hóa năng lượng',
    grade: 7,
    lessonId: 'bio-g7-b01',
    category: 'ly-thuyet',
    description: 'Bản chất trao đổi chất, các dạng năng lượng và mối quan hệ hai chiều giữa trao đổi chất và tích lũy/giải phóng năng lượng.',
  },
  {
    id: 'bio-quang-hop-co-che',
    name: 'Cơ chế & Phương trình quang hợp ở thực vật',
    grade: 7,
    lessonId: 'bio-g7-b02',
    category: 'ly-thuyet',
    description: 'Phương trình chữ quang hợp, bào quan lục lạp chứa chất diệp lục và đặc điểm cấu tạo lá phù hợp chức năng hấp thụ ánh sáng.',
  },
  {
    id: 'bio-yeu-to-quang-hop',
    name: 'Các yếu tố ảnh hưởng quang hợp & Ứng dụng',
    grade: 7,
    lessonId: 'bio-g7-b03',
    category: 'ly-thuyet',
    description: 'Ảnh hưởng của ánh sáng, nồng độ CO2, nước, nhiệt độ và ứng dụng xen canh, chiếu sáng nhân tạo trong trồng trọt.',
  },
  {
    id: 'bio-thuc-hanh-quang-hop',
    name: 'Thực hành chứng minh quang hợp',
    grade: 7,
    lessonId: 'bio-g7-b04',
    category: 'thi-nghiem',
    description: 'Quy trình thử tinh bột bằng thuốc thử iodine và thu khí oxygen làm bùng cháy que đóm tàn đỏ.',
  },
  {
    id: 'bio-ho-hap-te-bao',
    name: 'Hô hấp tế bào & Ty thể',
    grade: 7,
    lessonId: 'bio-g7-b05',
    category: 'ly-thuyet',
    description: 'Khái niệm, phương trình phân giải glucose tạo ATP tại ty thể và mối quan hệ đối lập - thống nhất với quang hợp.',
  },
  {
    id: 'bio-yeu-to-ho-hap',
    name: 'Yếu tố ảnh hưởng hô hấp & Bảo quản nông sản',
    grade: 7,
    lessonId: 'bio-g7-b06',
    category: 'ly-thuyet',
    description: 'Nhiệt độ, độ ẩm hạt, nồng độ O2/CO2 và các biện pháp bảo quản khô, bảo quản lạnh, hút chân không nông sản.',
  },
  {
    id: 'bio-thuc-hanh-ho-hap',
    name: 'Thực hành hô hấp ở thực vật',
    grade: 7,
    lessonId: 'bio-g7-b07',
    category: 'thi-nghiem',
    description: 'Thí nghiệm chứng minh hạt nảy mầm tỏa nhiệt, hút khí oxygen làm tắt que diêm và thải CO2 làm đục nước vôi trong.',
  },
  {
    id: 'bio-trao-doi-khi',
    name: 'Cơ chế trao đổi khí ở sinh vật',
    grade: 7,
    lessonId: 'bio-g7-b08',
    category: 'ly-thuyet',
    description: 'Cơ chế khuếch tán khí qua khí khổng của lá và 4 cơ quan trao đổi khí ở động vật (da, ống khí, mang, phổi).',
  },
  {
    id: 'bio-vai-tro-nuoc-dinh-duong',
    name: 'Vai trò của nước & Nhu cầu dinh dưỡng',
    grade: 7,
    lessonId: 'bio-g7-b09',
    category: 'tinh-toan',
    description: 'Vai trò dung môi hòa tan, điều hòa thân nhiệt, tính lượng nước cơ thể cần uống mỗi ngày theo công thức V = m × 40 mL.',
  },
  {
    id: 'bio-trao-doi-nuoc-thuc-vat',
    name: 'Dòng vận chuyển & Thoát hơi nước ở thực vật',
    grade: 7,
    lessonId: 'bio-g7-b10',
    category: 'ly-thuyet',
    description: 'Đặc điểm dòng mạch gỗ (nước, muối khoáng đi lên), dòng mạch rây (chất hữu cơ đi xuống) và vai trò thoát hơi nước qua khí khổng.',
  },
  {
    id: 'bio-trao-doi-nuoc-dong-vat',
    name: 'Trao đổi nước & Dinh dưỡng ở động vật',
    grade: 7,
    lessonId: 'bio-g7-b11',
    category: 'ly-thuyet',
    description: 'Con đường tiêu hóa thức ăn, hệ tuần hoàn vận chuyển máu và cơ quan bài tiết duy trì cân bằng nội môi.',
  },
  {
    id: 'bio-thuc-hanh-van-chuyen-nuoc',
    name: 'Thực hành vận chuyển nước & Thoát hơi nước',
    grade: 7,
    lessonId: 'bio-g7-b12',
    category: 'thi-nghiem',
    description: 'Thí nghiệm cành hoa/cần tây cắm nước mực đỏ và bọc túi nilon quan sát giọt nước ngưng tụ trên tán lá.',
  },
  {
    id: 'bio-cam-ung-tap-tinh',
    name: 'Cảm ứng ở sinh vật & Tập tính động vật',
    grade: 7,
    lessonId: 'bio-g7-b13',
    category: 'ly-thuyet',
    description: 'Tính hướng sáng, hướng trọng lực, hướng nước ở cây và phân biệt tập tính bẩm sinh với tập tính học được ở động vật.',
  },
  {
    id: 'bio-ung-dung-cam-ung-tap-tinh',
    name: 'Vận dụng cảm ứng & Tập tính vào thực tiễn',
    grade: 7,
    lessonId: 'bio-g7-b14',
    category: 'ly-thuyet',
    description: 'Làm giàn leo, thắp đèn kích thích ra hoa, huấn luyện thú cưng/chó nghiệp vụ và bẫy đèn diệt sâu bọ hại lúa.',
  },
  {
    id: 'bio-thuc-hanh-cam-ung',
    name: 'Thực hành quan sát hiện tượng cảm ứng',
    grade: 7,
    lessonId: 'bio-g7-b15',
    category: 'thi-nghiem',
    description: 'Thí nghiệm mầm cây vươn về nguồn sáng hộp kín, rễ đâm xuống theo trọng lực và phản ứng cụp lá cây trinh nữ.',
  },
  {
    id: 'bio-sinh-truong-phat-trien',
    name: 'Sinh trưởng, Phát triển & Vòng đời',
    grade: 7,
    lessonId: 'bio-g7-b16',
    category: 'ly-thuyet',
    description: 'Mô phân sinh đỉnh và bên, vòng năm sinh trưởng của gỗ, biến thái hoàn toàn ở bướm và không hoàn toàn ở châu chấu.',
  },
  {
    id: 'bio-ung-dung-sinh-truong-phat-trien',
    name: 'Ứng dụng sinh trưởng & Phát triển trong đời sống',
    grade: 7,
    lessonId: 'bio-g7-b17',
    category: 'ly-thuyet',
    description: 'Kỹ thuật bấm ngọn tỉa cành, điều khiển nhiệt độ/ánh sáng ra hoa trái vụ và diệt sâu bọ ở giai đoạn sâu non/bọ gậy.',
  },
  {
    id: 'bio-thuc-hanh-sinh-truong-phat-trien',
    name: 'Thực hành đo sinh trưởng & Mô tả vòng đời',
    grade: 7,
    lessonId: 'bio-g7-b18',
    category: 'thi-nghiem',
    description: 'Lập bảng theo dõi chiều cao mầm đậu, vẽ đồ thị sinh trưởng và phân tích sơ đồ vòng đời biến thái của ếch/bướm.',
  },
  {
    id: 'bio-sinh-san-vo-tinh',
    name: 'Sinh sản vô tính & Nhân giống sinh dưỡng',
    grade: 7,
    lessonId: 'bio-g7-b19',
    category: 'ly-thuyet',
    description: 'Sinh sản sinh dưỡng tự nhiên (thân củ, thân bò, rễ củ, lá) và kỹ thuật nhân tạo (giâm cành, chiết cành, ghép cành, nuôi cấy mô).',
  },
  {
    id: 'bio-sinh-san-huu-tinh-vs-vo-tinh',
    name: 'Phân biệt sinh sản vô tính & Sinh sản hữu tính',
    grade: 7,
    lessonId: 'bio-g7-b19',
    category: 'nhan-biet',
    description: 'So sánh cơ chế di truyền, số lượng cá thể tham gia và ý nghĩa thích nghi môi trường của sinh sản vô tính và hữu tính.',
  },
  {
    id: 'bio-sinh-san-huu-tinh',
    name: 'Sinh sản hữu tính ở thực vật có hoa & Động vật',
    grade: 7,
    lessonId: 'bio-g7-b20',
    category: 'ly-thuyet',
    description: 'Cấu tạo hoa, thụ phấn, thụ tinh biến noãn thành hạt và bầu thành quả; thụ tinh ngoài ở cá/ếch vs thụ tinh trong ở chim/thú.',
  },
  {
    id: 'bio-dieu-khien-sinh-san',
    name: 'Điều hòa & Điều khiển sinh sản ở sinh vật',
    grade: 7,
    lessonId: 'bio-g7-b21',
    category: 'ly-thuyet',
    description: 'Kỹ thuật thụ phấn nhân tạo cho ngô/dưa lưới, tiêm kích dục tố kích thích cá đẻ trứng và kiểm soát nhiệt độ ấp trứng điều khiển giới tính.',
  },
  {
    id: 'bio-co-the-thong-nhat',
    name: 'Cơ thể sinh vật là một thể thống nhất',
    grade: 7,
    lessonId: 'bio-g7-b22',
    category: 'ly-thuyet',
    description: 'Mối quan hệ hữu cơ giữa rễ - thân - lá, tế bào - cơ quan - cơ thể và khả năng thích nghi đồng bộ với môi trường sống.',
  },

  // SINH HỌC LỚP 8
  {
    id: 'bio-khai-quat-co-the-nguoi',
    name: 'Khái quát cơ thể người & Các hệ cơ quan',
    grade: 8,
    lessonId: 'bio-g8-b01',
    category: 'ly-thuyet',
    description: 'Cấu tạo chung các phần cơ thể, các hệ cơ quan phối hợp và 4 loại mô cơ bản (biểu bì, liên kết, cơ, thần kinh).',
  },
  {
    id: 'bio-he-van-dong',
    name: 'Hệ vận động & Phòng ngừa bệnh xương khớp',
    grade: 8,
    lessonId: 'bio-g8-b02',
    category: 'ly-thuyet',
    description: 'Cấu tạo bộ xương, khớp xương, sự phối hợp cơ xương khi co duỗi và các biện pháp chống cong vẹo cột sống.',
  },
  {
    id: 'bio-dinh-duong-tieu-hoa',
    name: 'Dinh dưỡng, Tiêu hóa & Năng lượng khẩu phần',
    grade: 8,
    lessonId: 'bio-g8-b03',
    category: 'tinh-toan',
    description: 'Tiêu hóa cơ học - hóa học qua các cơ quan tiêu hóa, vai trò enzym và tính toán năng lượng calo khẩu phần ăn.',
  },
  {
    id: 'bio-mau-tuan-hoan',
    name: 'Máu, Hệ tuần hoàn & Truyền máu an toàn',
    grade: 8,
    lessonId: 'bio-g8-b04',
    category: 'ly-thuyet',
    description: 'Thành phần máu, tế bào hồng cầu/bạch cầu/tiểu cầu, 2 vòng tuần hoàn, nguyên tắc truyền máu hệ ABO và sơ cứu xuất huyết.',
  },
  {
    id: 'bio-he-ho-hap',
    name: 'Hệ hô hấp, Thông khí & Bảo vệ đường thở',
    grade: 8,
    lessonId: 'bio-g8-b05',
    category: 'ly-thuyet',
    description: 'Đường dẫn khí và phổi, cơ chế thông khí nhờ cơ liên sườn và cơ hoành, trao đổi khí ở phế nang và phòng bệnh hô hấp.',
  },
  {
    id: 'bio-he-bai-tiet',
    name: 'Hệ bài tiết, Lọc máu & Tạo nước tiểu',
    grade: 8,
    lessonId: 'bio-g8-b06',
    category: 'ly-thuyet',
    description: 'Cấu tạo đơn vị chức năng nephron của thận, quá trình lọc máu tạo nước tiểu đầu và hấp thu lại tạo nước tiểu chính thức.',
  },
  {
    id: 'bio-moi-truong-trong',
    name: 'Cân bằng môi trường trong cơ thể (Nội môi)',
    grade: 8,
    lessonId: 'bio-g8-b07',
    category: 'ly-thuyet',
    description: 'Khái niệm môi trường trong (máu, dịch mô, bạch huyết) và cơ chế điều hòa đường huyết, áp suất thẩm thấu duy trì cân bằng nội môi.',
  },
  {
    id: 'bio-than-kinh-giac-quan',
    name: 'Hệ thần kinh, Não bộ & Các giác quan',
    grade: 8,
    lessonId: 'bio-g8-b08',
    category: 'ly-thuyet',
    description: 'Cấu tạo nơron, tủy sống, các phần não bộ, phản xạ có điều kiện - không điều kiện và cơ chế truyền cảm giác thị giác, thính giác.',
  },
  {
    id: 'bio-he-noi-tiet',
    name: 'Hệ nội tiết & Hormone điều hòa sinh lý',
    grade: 8,
    lessonId: 'bio-g8-b09',
    category: 'ly-thuyet',
    description: 'Tuyến yên, tuyến giáp, đảo tụy (insulin, glucagon), tuyến trên thận và vai trò hormone thể dịch trong điều hòa sinh trưởng, phát triển.',
  },
  {
    id: 'bio-da-dieu-hoa-than-nhiet',
    name: 'Cấu tạo da & Cơ chế điều hòa thân nhiệt',
    grade: 8,
    lessonId: 'bio-g8-b10',
    category: 'ly-thuyet',
    description: '3 lớp cấu tạo của da (biểu bì, bì, mỡ dưới da) và phản xạ run cơ, giãn mạch, toát mồ hôi để giữ thân nhiệt ổn định ~37°C.',
  },
  {
    id: 'bio-sinh-san-o-nguoi',
    name: 'Hệ sinh sản & Sức khỏe sinh sản vị thành niên',
    grade: 8,
    lessonId: 'bio-g8-b11',
    category: 'ly-thuyet',
    description: 'Cơ quan sinh dục nam/nữ, quá trình thụ tinh làm tổ, các biện pháp tránh thai an toàn và phòng tránh bệnh lây truyền qua đường tình dục.',
  },
  {
    id: 'bio-moi-truong-sinh-thai',
    name: 'Môi trường sống & Các nhân tố sinh thái',
    grade: 8,
    lessonId: 'bio-g8-b12',
    category: 'ly-thuyet',
    description: '4 môi trường sống, phân loại nhân tố vô sinh - hữu sinh và quy luật giới hạn sinh thái (điểm chết, khoảng thuận lợi).',
  },
  {
    id: 'bio-quan-the-sinh-vat',
    name: 'Quần thể sinh vật & Mật độ cá thể',
    grade: 8,
    lessonId: 'bio-g8-b13',
    category: 'tinh-toan',
    description: 'Khái niệm quần thể, tỉ lệ giới tính, tháp tuổi, biến động số lượng và tính toán mật độ cá thể trên diện tích/thể tích (D = N/S).',
  },
  {
    id: 'bio-quan-xa-sinh-vat',
    name: 'Quần xã sinh vật, Quan hệ sinh thái & Khống chế',
    grade: 8,
    lessonId: 'bio-g8-b14',
    category: 'nhan-biet',
    description: 'Loài ưu thế vs loài đặc trưng, phân biệt cộng sinh / hội sinh / cạnh tranh / kí sinh và ứng dụng thiên địch trong khống chế sinh học.',
  },
  {
    id: 'bio-he-sinh-thai',
    name: 'Hệ sinh thái, Chuỗi/Lưới thức ăn & Tháp năng lượng',
    grade: 8,
    lessonId: 'bio-g8-b15',
    category: 'ly-thuyet',
    description: 'Cấu trúc hệ sinh thái (sinh cảnh + quần xã), bậc dinh dưỡng, lưới thức ăn phức tạp và quy luật tháp năng lượng hao hụt 90%.',
  },
  {
    id: 'bio-sinh-quyen',
    name: 'Sinh quyển & Các khu sinh học (Biomes)',
    grade: 8,
    lessonId: 'bio-g8-b16',
    category: 'ly-thuyet',
    description: 'Phạm vi giới hạn sinh quyển, các khu sinh học trên cạn (rừng nhiệt đới, taiga, thảo nguyên, đài nguyên) và dưới nước (nước ngọt, rạn san hô).',
  },
  {
    id: 'bio-can-bang-tu-nhien',
    name: 'Trạng thái cân bằng tự nhiên & Tự điều chỉnh',
    grade: 8,
    lessonId: 'bio-g8-b17',
    category: 'ly-thuyet',
    description: 'Bản chất cân bằng động, tương tác con mồi - kẻ săn mồi, tác hại nạn phá rừng và sinh vật ngoại lai xâm lấn.',
  },
  {
    id: 'bio-bao-ve-moi-truong',
    name: 'Ô nhiễm môi trường, Kinh tế 3R & Hành động xanh',
    grade: 8,
    lessonId: 'bio-g8-b18',
    category: 'ly-thuyet',
    description: 'Các dạng ô nhiễm (khí thải, nước phú dưỡng, đất ngấm kim loại nặng, vi nhựa), hiệu ứng nhà kính và nguyên tắc 3R bảo vệ môi trường.',
  },
  // LỚP 9 - SINH HỌC
  {
    id: 'bio9-khai-quat-di-truyen',
    name: 'Khái quát di truyền học & Phương pháp Mendel',
    grade: 9,
    lessonId: 'bio-g9-b01',
    category: 'ly-thuyet',
    description: 'Di truyền và biến dị, cặp tính trạng tương phản, thể đồng hợp/dị hợp và phương pháp phân tích cơ thể lai của Mendel.',
  },
  {
    id: 'bio9-quy-luat-mendel',
    name: 'Các quy luật di truyền của Mendel & Phép lai phân tích',
    grade: 9,
    lessonId: 'bio-g9-b02',
    category: 'tinh-toan',
    description: 'Quy luật phân li (3:1), phân li độc lập (9:3:3:1), phép lai phân tích xác định kiểu gen và biến dị tổ hợp.',
  },
  {
    id: 'bio9-nucleic-acid-gene',
    name: 'Cấu trúc DNA, RNA & Nguyên tắc bổ sung',
    grade: 9,
    lessonId: 'bio-g9-b03',
    category: 'ly-thuyet',
    description: 'Cấu trúc xoắn kép DNA, 4 loại nucleotide A, T, G, C, liên kết hydrogen theo NTBS, các loại RNA và khái niệm gene.',
  },
  {
    id: 'bio9-tai-ban-phien-ma',
    name: 'Tái bản DNA & Phiên mã tạo RNA',
    grade: 9,
    lessonId: 'bio-g9-b04',
    category: 'ly-thuyet',
    description: 'Nguyên tắc bán bảo tồn và bổ sung trong tái bản DNA, cơ chế enzyme RNA polymerase tổng hợp mRNA từ mạch gốc 3\'-5\'.',
  },
  {
    id: 'bio9-dich-ma-protein',
    name: 'Mã di truyền, Dịch mã & Sơ đồ Central Dogma',
    grade: 9,
    lessonId: 'bio-g9-b05',
    category: 'ly-thuyet',
    description: 'Bộ ba codon trên mRNA, vai trò tRNA và ribosome, sơ đồ dòng thông tin di truyền: Gene → mRNA → Protein → Tính trạng.',
  },
  {
    id: 'bio9-dot-bien-gene',
    name: 'Đột biến gene & Tác động sinh học',
    grade: 9,
    lessonId: 'bio-g9-b06',
    category: 'nhan-biet',
    description: 'Các dạng đột biến điểm (thay thế, thêm, mất cặp nu), hiện tượng dịch khung đọc mã và vai trò trong chọn giống/tiến hóa.',
  },
  {
    id: 'bio9-nhiem-sac-the',
    name: 'Cấu trúc nhiễm sắc thể & Bộ NST đặc trưng loài',
    grade: 9,
    lessonId: 'bio-g9-b07',
    category: 'ly-thuyet',
    description: 'DNA quấn quanh histone, cấu trúc chromatid và tâm động tại kì giữa, bộ NST lưỡng bội (2n) và đơn bội (n).',
  },
  {
    id: 'bio9-nguyen-phan-giam-phan',
    name: 'Nguyên phân, Giảm phân & Biến dị tổ hợp',
    grade: 9,
    lessonId: 'bio-g9-b08',
    category: 'nhan-biet',
    description: 'Diễn biến NST qua 4 kì nguyên phân (xếp 1 hàng) và giảm phân (xếp 2 hàng ở kì giữa I), sự phân li và chẻ tâm động.',
  },
  {
    id: 'bio9-nst-gioi-tinh',
    name: 'NST giới tính & Cơ chế xác định giới tính',
    grade: 9,
    lessonId: 'bio-g9-b09',
    category: 'ly-thuyet',
    description: 'Cặp NST XX/XY, cơ chế thụ tinh xác định tỉ lệ 1 đực : 1 cái ở người và sự phân hóa giới tính theo môi trường.',
  },
  {
    id: 'bio9-di-truyen-lien-ket',
    name: 'Di truyền liên kết & Thí nghiệm Morgan',
    grade: 9,
    lessonId: 'bio-g9-b10',
    category: 'tinh-toan',
    description: 'Hiện tượng các gen trên cùng 1 NST di truyền cùng nhau, nhóm gen liên kết (n) và tỉ lệ lai phân tích 1:1 ở ruồi giấm.',
  },
  {
    id: 'bio9-dot-bien-nst',
    name: 'Đột biến cấu trúc & Số lượng nhiễm sắc thể',
    grade: 9,
    lessonId: 'bio-g9-b11',
    category: 'nhan-biet',
    description: 'Mất, lặp, đảo, chuyển đoạn; thể lệch bội (2n±1), thể đa bội (3n, 4n) và ứng dụng tạo giống cây trồng không hạt.',
  },
  {
    id: 'bio9-di-truyen-nguoi',
    name: 'Di truyền y học người & Nghiên cứu phả hệ',
    grade: 9,
    lessonId: 'bio-g9-b12',
    category: 'ly-thuyet',
    description: 'Phương pháp phả hệ, hội chứng Đao (3 NST 21), Turner (XO), Klinefelter (XXY), bệnh mù màu/máu khó đông liên kết giới tính.',
  },
  {
    id: 'bio9-cong-nghe-di-truyen',
    name: 'Công nghệ tế bào & Công nghệ gene GMO',
    grade: 9,
    lessonId: 'bio-g9-b13',
    category: 'thi-nghiem',
    description: 'Nuôi cấy mô, nhân bản vô tính cừu Dolly, kỹ thuật chuyển gen dùng ADN tái tổ hợp (restrictase + ligase) và sinh vật GMO.',
  },
  {
    id: 'bio9-tien-hoa-chon-loc',
    name: 'Bằng chứng tiến hóa & Các hình thức chọn lọc',
    grade: 9,
    lessonId: 'bio-g9-b14',
    category: 'nhan-biet',
    description: 'Cơ quan tương đồng vs cơ quan tương tự, cơ quan thoái hóa, hóa thạch, phân biệt chọn lọc tự nhiên và nhân tạo.',
  },
  {
    id: 'bio9-co-che-tien-hoa',
    name: 'Thuyết tiến hóa tổng hợp & Cơ chế hình thành loài',
    grade: 9,
    lessonId: 'bio-g9-b15',
    category: 'ly-thuyet',
    description: 'Các nhân tố tiến hóa (đột biến, giao phối, CLTN), quá trình hình thành đặc điểm thích nghi và cách li sinh sản.',
  },
  {
    id: 'bio9-nguon-goc-su-song',
    name: 'Lịch sử phát triển sự sống qua 5 đại địa chất',
    grade: 9,
    lessonId: 'bio-g9-b16',
    category: 'ly-thuyet',
    description: '3 giai đoạn tiến hóa (hóa học, tiền sinh học, sinh học) và các sinh vật đại diện từ Đại Thái cổ đến Tân sinh.',
  },
];

export function getSkillsByGrade(grade: 6 | 7 | 8 | 9, subject?: 'chem' | 'physics' | 'bio'): Skill[] {
  return SKILLS.filter((s) => {
    if (s.grade !== grade) return false;
    if (subject === 'bio') return s.lessonId.startsWith('bio-');
    if (subject === 'physics') return s.lessonId.startsWith('phy-');
    if (subject === 'chem') return s.lessonId.startsWith('g');
    return true;
  });
}

export function getSkillsByLesson(lessonId: string): Skill[] {
  return SKILLS.filter((s) => s.lessonId === lessonId);
}

export function getSkillById(id: string): Skill | undefined {
  return SKILLS.find((s) => s.id === id);
}
